# Generated by Django 3.1.2 on 2020-10-28 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grpwork', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='Centres',
            new_name='centres',
        ),
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Neighbourhood',
            new_name='neighbourhood',
        ),
    ]
